version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "8300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: wpesycrm
      MYSQL_USER: root
      MYSQL_PASSWORD: myrootpass
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8301:80"
    environment:
      PMA_HOST: db
      PMA_PASSWORD: myrootpass
      MYSQL_ROOT_PASSWORD: myrootpass
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8302:80"
      - "8443:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: myrootpass
      WORDPRESS_DB_NAME: wpesycrm
    networks:
      - wpsite

volumes:
  db_data: {}
networks:
  wpsite: {}
